name: Deploy docs
on:
  push:
    paths:
      - 'mkdocs.yaml'
      - 'docs/**'
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy_docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:trixie-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ runner.os }}-${{ hashFiles('mkdocs.yaml', 'pyproject.toml', 'uv.lock') }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
